// <auto-generated />
using System;
using LibraryManagement.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.DAL.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260512000036_InitialState")]
    partial class InitialState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityID"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ActivityID");

                    b.HasIndex("TenantID");

                    b.HasIndex("UserID", "CreatedAt");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .IsFixedLength();

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("YearPublished")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("smallint");

                    b.HasKey("BookID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("TenantID");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.BookCopy", b =>
                {
                    b.Property<int>("BookCopyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookCopyID"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookCopyID");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BookID");

                    b.HasIndex("TenantID");

                    b.ToTable("BookCopies", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrowing", b =>
                {
                    b.Property<int>("BorrowingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowingID"));

                    b.Property<int>("BookCopyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InitialFees")
                        .HasColumnType("decimal(18.2)");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BorrowingID");

                    b.HasIndex("BookCopyID");

                    b.HasIndex("MemberID");

                    b.HasIndex("TenantID");

                    b.ToTable("Borrowings", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Programming",
                            Description = "Software development, languages, and tools"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Computer Science",
                            Description = "Theoretical foundations, algorithms, and AI"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Cybersecurity",
                            Description = "Network security, ethical hacking, and cryptography"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "History",
                            Description = "World history, civilizations, and biographies"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Philosophy",
                            Description = "Classical and modern philosophical thoughts"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Psychology",
                            Description = "Human behavior, mental health, and social psychology"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Fiction",
                            Description = "Novels, short stories, and literary works"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Science Fiction",
                            Description = "Space exploration, time travel, and futuristic tech"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Poetry",
                            Description = "Classical and contemporary poetic collections"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Astronomy & Physics",
                            Description = "Space, cosmos, quantum mechanics, and astrophysics"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Mathematics",
                            Description = "Pure and applied mathematics, statistics, and logic"
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Business & Finance",
                            Description = "Economy, management, and personal finance"
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "Self-Help",
                            Description = "Personal development, productivity, and leadership"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Fine", b =>
                {
                    b.Property<int>("FineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FineID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BorrowingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WaiveReason")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FineID");

                    b.HasIndex("BorrowingID")
                        .IsUnique();

                    b.HasIndex("MemberID");

                    b.HasIndex("TenantID");

                    b.ToTable("Fines", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.GlobalSettings", b =>
                {
                    b.Property<int>("SettingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingsID"));

                    b.Property<int>("DefaultBorrowingDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(14);

                    b.Property<decimal>("DefaultFinePerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18.2)")
                        .HasDefaultValue(10.0m);

                    b.Property<bool>("IsLibraryOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MaxBooksPerMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<decimal>("MaxFineLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18.2)")
                        .HasDefaultValue(100.0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SettingsID");

                    b.HasIndex("TenantID")
                        .IsUnique();

                    b.ToTable("GlobalSettings", (string)null);

                    b.HasData(
                        new
                        {
                            SettingsID = 1,
                            DefaultBorrowingDays = 14,
                            DefaultFinePerDay = 10.0m,
                            IsLibraryOpen = true,
                            LastUpdated = new DateTime(2026, 5, 12, 0, 0, 35, 687, DateTimeKind.Utc).AddTicks(454),
                            MaxBooksPerMember = 5,
                            MaxFineLimit = 100.0m,
                            Name = "LibCore",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            SettingsID = 2,
                            DefaultBorrowingDays = 14,
                            DefaultFinePerDay = 15.0m,
                            IsLibraryOpen = true,
                            LastUpdated = new DateTime(2026, 5, 12, 0, 0, 35, 687, DateTimeKind.Utc).AddTicks(459),
                            MaxBooksPerMember = 10,
                            MaxFineLimit = 200.0m,
                            Name = "LibCore",
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.HasIndex("TenantID");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 12, 0, 0, 35, 682, DateTimeKind.Utc).AddTicks(7261),
                            PersonID = 2,
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            MemberID = 2,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 12, 0, 0, 35, 682, DateTimeKind.Utc).AddTicks(7266),
                            PersonID = 1,
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            MemberID = 3,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 12, 0, 0, 35, 682, DateTimeKind.Utc).AddTicks(7268),
                            PersonID = 4,
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            MemberID = 4,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 12, 0, 0, 35, 682, DateTimeKind.Utc).AddTicks(7270),
                            PersonID = 3,
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            MemberID = 5,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 12, 0, 0, 35, 682, DateTimeKind.Utc).AddTicks(7271),
                            PersonID = 6,
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            MemberID = 6,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 12, 0, 0, 35, 682, DateTimeKind.Utc).AddTicks(7273),
                            PersonID = 5,
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            MemberID = 7,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 12, 0, 0, 35, 682, DateTimeKind.Utc).AddTicks(7275),
                            PersonID = 7,
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NationalNumber")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("TenantID");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            Address = "Agdal, Rabat",
                            City = "Rabat",
                            Email = "ahmed.alami@gmail.com",
                            FirstName = "Ahmed",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Alami",
                            NationalNumber = "IC122065",
                            Phone = "0612345678",
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            PersonID = 2,
                            Address = "Gueliz, Marrakech",
                            City = "Marrakech",
                            Email = "fatima.ezzahra@outlook.com",
                            FirstName = "Fatima",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Zahra",
                            NationalNumber = "IC122068",
                            Phone = "0623456789",
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            PersonID = 3,
                            Address = "Maarif, Casablanca",
                            City = "Casablanca",
                            Email = "youssef.idrissi@yahoo.com",
                            FirstName = "Youssef",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Idrissi",
                            NationalNumber = "IC922065",
                            Phone = "0634567890",
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            PersonID = 4,
                            Address = "Ville Nouvelle, Fes",
                            City = "Fes",
                            Email = "sanaa.bennani@gmail.com",
                            FirstName = "Sanaa",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Bennani",
                            NationalNumber = "IC922965",
                            Phone = "0645678901",
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            PersonID = 5,
                            Address = "Malabata, Tanger",
                            City = "Tanger",
                            Email = "omar.mansouri@hotmail.com",
                            FirstName = "Omar",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Mansouri",
                            NationalNumber = "IC128493",
                            Phone = "0656789012",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            PersonID = 6,
                            Address = "Hay Salam, Agadir",
                            City = "Agadir",
                            Email = "laila.tazi@gmail.com",
                            FirstName = "Laila",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Tazi",
                            NationalNumber = "I907065",
                            Phone = "0667890123",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            PersonID = 7,
                            Address = "Ouled Ayad, Beni Mellal",
                            City = "Beni Mellal",
                            Email = "karim.sabbahi@icloud.com",
                            FirstName = "Karim",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Sabbahi",
                            NationalNumber = "IC87409",
                            Phone = "0678901234",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            PersonID = 8,
                            Address = "Nansria, Oujda",
                            City = "Oujda",
                            Email = "meryem.fassi@gmail.com",
                            FirstName = "Meryem",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Fassi",
                            NationalNumber = "IC008571",
                            Phone = "0689012345",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            PersonID = 9,
                            Address = "Dakhla, Meknes",
                            City = "Meknes",
                            Email = "hamza.radi@live.com",
                            FirstName = "Hamza",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Radi",
                            NationalNumber = "IC124598",
                            Phone = "0690123456",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            PersonID = 10,
                            Address = "Mohammedia Center",
                            City = "Mohammedia",
                            Email = "salma.amrani@gmail.com",
                            FirstName = "Salma",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Amrani",
                            NationalNumber = "IC248382",
                            Phone = "0601234567",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            PersonID = 11,
                            Address = "Ait Alla , Tabia , Azilal",
                            City = "Azilal",
                            Email = "Freeh11@gmail.com",
                            FirstName = "Abdenabi",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Khaldi",
                            NationalNumber = "IC188555",
                            Phone = "0644353219",
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TenantID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Librarian"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("ar");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("UTC");

                    b.HasKey("TenantID");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            TenantID = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultLanguage = "ar",
                            Identifier = "casablanca-main",
                            IsActive = true,
                            Name = "مكتبة الدار البيضاء المركزية",
                            TimeZone = "W. Central Africa Standard Time"
                        },
                        new
                        {
                            TenantID = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultLanguage = "en",
                            Identifier = "rabat-digital",
                            IsActive = true,
                            Name = "Rabat International Library",
                            TimeZone = "UTC"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("TenantID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.BookCopy", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrowing", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.BookCopy", "BookCopy")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookCopyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Fine", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Borrowing", "Borrowing")
                        .WithOne("Fine")
                        .HasForeignKey("LibraryManagement.Domain.Entities.Fine", "BorrowingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Member", "Member")
                        .WithMany("Fines")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Borrowing");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.GlobalSettings", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithOne("GlobalSettings")
                        .HasForeignKey("LibraryManagement.Domain.Entities.GlobalSettings", "TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LibraryManagement.Domain.Entities.Member", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Person", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LibraryManagement.Domain.Entities.User", "PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Users")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.BookCopy", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrowing", b =>
                {
                    b.Navigation("Fine");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Navigation("GlobalSettings")
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
