// <auto-generated />
using System;
using LibraryManagement.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.DAL.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260116130430_AddDataSeedingToUser")]
    partial class AddDataSeedingToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityID"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ActivityID");

                    b.HasIndex("UserID", "CreatedAt");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short?>("YearPublished")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("smallint");

                    b.HasKey("BookID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryID = 1,
                            ImagePath = "images/gatsby.jpg",
                            IsActive = true,
                            Publisher = "Scribner",
                            Quantity = (short)10,
                            Title = "The Great Gatsby",
                            YearPublished = (short)1925
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Stephen Hawking",
                            CategoryID = 2,
                            ImagePath = "images/hawking_brief.jpg",
                            IsActive = true,
                            Publisher = "Bantam Books",
                            Quantity = (short)5,
                            Title = "A Brief History of Time",
                            YearPublished = (short)1988
                        },
                        new
                        {
                            BookID = 3,
                            Author = "George Orwell",
                            CategoryID = 1,
                            ImagePath = "images/1984.jpg",
                            IsActive = true,
                            Publisher = "Secker & Warburg",
                            Quantity = (short)15,
                            Title = "1984",
                            YearPublished = (short)1949
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Robert C. Martin",
                            CategoryID = 3,
                            ImagePath = "images/clean-code.jpg",
                            IsActive = true,
                            Publisher = "Prentice Hall",
                            Quantity = (short)8,
                            Title = "Clean Code",
                            YearPublished = (short)2008
                        },
                        new
                        {
                            BookID = 5,
                            Author = "J.R.R. Tolkien",
                            CategoryID = 1,
                            ImagePath = "images/hobbit.jpg",
                            IsActive = true,
                            Publisher = "George Allen & Unwin",
                            Quantity = (short)12,
                            Title = "The Hobbit",
                            YearPublished = (short)1937
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrowing", b =>
                {
                    b.Property<int>("BorrowingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowingID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BorrowingID");

                    b.HasIndex("BookID");

                    b.HasIndex("MemberID");

                    b.ToTable("Borrowings", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Programming",
                            Description = "Software development books"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "History",
                            Description = "World history and biographies"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Fiction",
                            Description = "Novels and stories"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PersonID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            Address = "Agdal, Rabat",
                            City = "Rabat",
                            Email = "ahmed.alami@gmail.com",
                            FirstName = "Ahmed",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Alami",
                            Phone = "0612345678"
                        },
                        new
                        {
                            PersonID = 2,
                            Address = "Gueliz, Marrakech",
                            City = "Marrakech",
                            Email = "fatima.ezzahra@outlook.com",
                            FirstName = "Fatima",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Zahra",
                            Phone = "0623456789"
                        },
                        new
                        {
                            PersonID = 3,
                            Address = "Maarif, Casablanca",
                            City = "Casablanca",
                            Email = "youssef.idrissi@yahoo.com",
                            FirstName = "Youssef",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Idrissi",
                            Phone = "0634567890"
                        },
                        new
                        {
                            PersonID = 4,
                            Address = "Ville Nouvelle, Fes",
                            City = "Fes",
                            Email = "sanaa.bennani@gmail.com",
                            FirstName = "Sanaa",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Bennani",
                            Phone = "0645678901"
                        },
                        new
                        {
                            PersonID = 5,
                            Address = "Malabata, Tanger",
                            City = "Tanger",
                            Email = "omar.mansouri@hotmail.com",
                            FirstName = "Omar",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Mansouri",
                            Phone = "0656789012"
                        },
                        new
                        {
                            PersonID = 6,
                            Address = "Hay Salam, Agadir",
                            City = "Agadir",
                            Email = "laila.tazi@gmail.com",
                            FirstName = "Laila",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Tazi",
                            Phone = "0667890123"
                        },
                        new
                        {
                            PersonID = 7,
                            Address = "Ouled Ayad, Beni Mellal",
                            City = "Beni Mellal",
                            Email = "karim.sabbahi@icloud.com",
                            FirstName = "Karim",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Sabbahi",
                            Phone = "0678901234"
                        },
                        new
                        {
                            PersonID = 8,
                            Address = "Nansria, Oujda",
                            City = "Oujda",
                            Email = "meryem.fassi@gmail.com",
                            FirstName = "Meryem",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Fassi",
                            Phone = "0689012345"
                        },
                        new
                        {
                            PersonID = 9,
                            Address = "Dakhla, Meknes",
                            City = "Meknes",
                            Email = "hamza.radi@live.com",
                            FirstName = "Hamza",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Radi",
                            Phone = "0690123456"
                        },
                        new
                        {
                            PersonID = 10,
                            Address = "Mohammedia Center",
                            City = "Mohammedia",
                            Email = "salma.amrani@gmail.com",
                            FirstName = "Salma",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Amrani",
                            Phone = "0601234567"
                        },
                        new
                        {
                            PersonID = 11,
                            Address = "Ait Alla , Tabia , Azilal",
                            City = "Azilal",
                            Email = "Freeh11@gmail.com",
                            FirstName = "Abdenabi",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Khaldi",
                            Phone = "0644353219"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Librarian"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 13, 4, 29, 976, DateTimeKind.Utc).AddTicks(102),
                            IsActive = true,
                            IsBlocked = false,
                            Password = "123456",
                            PersonID = 11,
                            RoleID = 1,
                            Username = "abdokhal12"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(2026, 1, 16, 13, 4, 29, 976, DateTimeKind.Utc).AddTicks(105),
                            IsActive = true,
                            IsBlocked = false,
                            Password = "123456",
                            PersonID = 2,
                            RoleID = 2,
                            Username = "fatima12"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrowing", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LibraryManagement.Domain.Entities.Member", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LibraryManagement.Domain.Entities.User", "PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
