// <auto-generated />
using System;
using LibraryManagement.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.DAL.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityID"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ActivityID");

                    b.HasIndex("UserID", "CreatedAt");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("YearPublished")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("smallint");

                    b.HasKey("BookID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic novel set in the Roaring Twenties, exploring themes of wealth, love, and the American Dream through the mysterious Jay Gatsby.",
                            ISBN = "9780743273565",
                            ImagePath = "7766677788.jpg",
                            IsActive = true,
                            Publisher = "Scribner",
                            Title = "The Great Gatsby",
                            YearPublished = (short)1925
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Stephen Hawking",
                            CategoryID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A landmark in scientific writing by one of the world's great minds, explaining the complex concepts of cosmology—from the Big Bang to black holes—in simple terms.",
                            ISBN = "9780553380163",
                            ImagePath = "7778899900008.jpg",
                            IsActive = true,
                            Publisher = "Bantam Books",
                            Title = "A Brief History of Time",
                            YearPublished = (short)1988
                        },
                        new
                        {
                            BookID = 3,
                            Author = "George Orwell",
                            CategoryID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A chilling dystopian masterpiece that explores the dangers of totalitarianism, surveillance, and the manipulation of truth in a society ruled by Big Brother.",
                            ISBN = "9780451524935",
                            ImagePath = "54456677.jpg",
                            IsActive = true,
                            Publisher = "Secker & Warburg",
                            Title = "1984",
                            YearPublished = (short)1949
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Robert C. Martin",
                            CategoryID = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An essential guide for software developers, focusing on best practices, principles, and patterns to write code that is readable, maintainable, and professional.",
                            ISBN = "9780132350884",
                            ImagePath = "67778887776.jpg",
                            IsActive = true,
                            Publisher = "Prentice Hall",
                            Title = "Clean Code",
                            YearPublished = (short)2008
                        },
                        new
                        {
                            BookID = 5,
                            Author = "J.R.R. Tolkien",
                            CategoryID = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The unforgettable journey of Bilbo Baggins as he travels through Middle-earth to reclaim a treasure guarded by the dragon Smaug. A prelude to The Lord of the Rings.",
                            ISBN = "9780547928227",
                            ImagePath = "7776666778.jpg",
                            IsActive = true,
                            Publisher = "George Allen & Unwin",
                            Title = "The Hobbit",
                            YearPublished = (short)1937
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.BookCopy", b =>
                {
                    b.Property<int>("BookCopyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookCopyID"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookCopyID");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BookID");

                    b.ToTable("BookCopies", (string)null);

                    b.HasData(
                        new
                        {
                            BookCopyID = 1,
                            Barcode = "BC-101-01",
                            BookID = 1,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 2,
                            Barcode = "BC-101-02",
                            BookID = 1,
                            Condition = "Good",
                            IsActive = true,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BookCopyID = 3,
                            Barcode = "BC-101-03",
                            BookID = 1,
                            Condition = "Good",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 4,
                            Barcode = "BC-101-04",
                            BookID = 1,
                            Condition = "Torn Pages",
                            IsActive = true,
                            Status = "Damaged"
                        },
                        new
                        {
                            BookCopyID = 5,
                            Barcode = "BC-101-05",
                            BookID = 1,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 6,
                            Barcode = "BC-202-01",
                            BookID = 2,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 7,
                            Barcode = "BC-202-02",
                            BookID = 2,
                            Condition = "Good",
                            IsActive = true,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BookCopyID = 8,
                            Barcode = "BC-202-03",
                            BookID = 2,
                            Condition = "Excellent",
                            IsActive = true,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BookCopyID = 9,
                            Barcode = "BC-202-04",
                            BookID = 2,
                            Condition = "Missing",
                            IsActive = true,
                            Status = "Lost"
                        },
                        new
                        {
                            BookCopyID = 10,
                            Barcode = "BC-202-05",
                            BookID = 2,
                            Condition = "Good",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 11,
                            Barcode = "BC-303-01",
                            BookID = 3,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 12,
                            Barcode = "BC-303-02",
                            BookID = 3,
                            Condition = "Good",
                            IsActive = true,
                            Status = "Reserved"
                        },
                        new
                        {
                            BookCopyID = 13,
                            Barcode = "BC-303-03",
                            BookID = 3,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 14,
                            Barcode = "BC-303-04",
                            BookID = 3,
                            Condition = "Fair",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 15,
                            Barcode = "BC-303-05",
                            BookID = 3,
                            Condition = "Water Damage",
                            IsActive = true,
                            Status = "Damaged"
                        },
                        new
                        {
                            BookCopyID = 16,
                            Barcode = "BC-404-01",
                            BookID = 4,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 17,
                            Barcode = "BC-404-02",
                            BookID = 4,
                            Condition = "Good",
                            IsActive = true,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BookCopyID = 18,
                            Barcode = "BC-404-03",
                            BookID = 4,
                            Condition = "Good",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 19,
                            Barcode = "BC-404-04",
                            BookID = 4,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        },
                        new
                        {
                            BookCopyID = 20,
                            Barcode = "BC-404-05",
                            BookID = 4,
                            Condition = "New",
                            IsActive = true,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrowing", b =>
                {
                    b.Property<int>("BorrowingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowingID"));

                    b.Property<int>("BookCopyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BorrowingID");

                    b.HasIndex("BookCopyID");

                    b.HasIndex("MemberID");

                    b.ToTable("Borrowings", (string)null);

                    b.HasData(
                        new
                        {
                            BorrowingID = 1,
                            BookCopyID = 2,
                            BorrowingDate = new DateTime(2026, 2, 2, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2940),
                            DueDate = new DateTime(2026, 2, 6, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2942),
                            IsCanceled = false,
                            MemberID = 1,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BorrowingID = 2,
                            BookCopyID = 7,
                            BorrowingDate = new DateTime(2026, 2, 2, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2948),
                            DueDate = new DateTime(2026, 2, 7, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2949),
                            IsCanceled = false,
                            MemberID = 2,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BorrowingID = 3,
                            BookCopyID = 8,
                            BorrowingDate = new DateTime(2026, 2, 2, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2951),
                            DueDate = new DateTime(2026, 2, 4, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2951),
                            IsCanceled = false,
                            MemberID = 3,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BorrowingID = 4,
                            BookCopyID = 17,
                            BorrowingDate = new DateTime(2026, 2, 2, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2953),
                            DueDate = new DateTime(2026, 2, 6, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2954),
                            IsCanceled = false,
                            MemberID = 3,
                            Status = "Borrowed"
                        },
                        new
                        {
                            BorrowingID = 5,
                            BookCopyID = 2,
                            BorrowingDate = new DateTime(2026, 1, 2, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2955),
                            DueDate = new DateTime(2026, 1, 9, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2963),
                            IsCanceled = false,
                            MemberID = 7,
                            ReturnDate = new DateTime(2026, 1, 7, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2964),
                            Status = "Returned"
                        },
                        new
                        {
                            BorrowingID = 6,
                            BookCopyID = 12,
                            BorrowingDate = new DateTime(2026, 2, 2, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2968),
                            DueDate = new DateTime(2026, 2, 8, 19, 36, 36, 512, DateTimeKind.Utc).AddTicks(2968),
                            IsCanceled = false,
                            MemberID = 7,
                            Status = "Borrowed"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Programming",
                            Description = "Software development books"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "History",
                            Description = "World history and biographies"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Fiction",
                            Description = "Novels and stories"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 2, 2, 19, 36, 36, 513, DateTimeKind.Utc).AddTicks(215),
                            PersonID = 2
                        },
                        new
                        {
                            MemberID = 2,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 2, 2, 19, 36, 36, 513, DateTimeKind.Utc).AddTicks(218),
                            PersonID = 1
                        },
                        new
                        {
                            MemberID = 3,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 2, 2, 19, 36, 36, 513, DateTimeKind.Utc).AddTicks(219),
                            PersonID = 4
                        },
                        new
                        {
                            MemberID = 4,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 2, 2, 19, 36, 36, 513, DateTimeKind.Utc).AddTicks(220),
                            PersonID = 3
                        },
                        new
                        {
                            MemberID = 5,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 2, 2, 19, 36, 36, 513, DateTimeKind.Utc).AddTicks(222),
                            PersonID = 6
                        },
                        new
                        {
                            MemberID = 6,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 2, 2, 19, 36, 36, 513, DateTimeKind.Utc).AddTicks(223),
                            PersonID = 5
                        },
                        new
                        {
                            MemberID = 7,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 2, 2, 19, 36, 36, 513, DateTimeKind.Utc).AddTicks(224),
                            PersonID = 7
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PersonID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            Address = "Agdal, Rabat",
                            City = "Rabat",
                            Email = "ahmed.alami@gmail.com",
                            FirstName = "Ahmed",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Alami",
                            Phone = "0612345678"
                        },
                        new
                        {
                            PersonID = 2,
                            Address = "Gueliz, Marrakech",
                            City = "Marrakech",
                            Email = "fatima.ezzahra@outlook.com",
                            FirstName = "Fatima",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Zahra",
                            Phone = "0623456789"
                        },
                        new
                        {
                            PersonID = 3,
                            Address = "Maarif, Casablanca",
                            City = "Casablanca",
                            Email = "youssef.idrissi@yahoo.com",
                            FirstName = "Youssef",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Idrissi",
                            Phone = "0634567890"
                        },
                        new
                        {
                            PersonID = 4,
                            Address = "Ville Nouvelle, Fes",
                            City = "Fes",
                            Email = "sanaa.bennani@gmail.com",
                            FirstName = "Sanaa",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Bennani",
                            Phone = "0645678901"
                        },
                        new
                        {
                            PersonID = 5,
                            Address = "Malabata, Tanger",
                            City = "Tanger",
                            Email = "omar.mansouri@hotmail.com",
                            FirstName = "Omar",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Mansouri",
                            Phone = "0656789012"
                        },
                        new
                        {
                            PersonID = 6,
                            Address = "Hay Salam, Agadir",
                            City = "Agadir",
                            Email = "laila.tazi@gmail.com",
                            FirstName = "Laila",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Tazi",
                            Phone = "0667890123"
                        },
                        new
                        {
                            PersonID = 7,
                            Address = "Ouled Ayad, Beni Mellal",
                            City = "Beni Mellal",
                            Email = "karim.sabbahi@icloud.com",
                            FirstName = "Karim",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Sabbahi",
                            Phone = "0678901234"
                        },
                        new
                        {
                            PersonID = 8,
                            Address = "Nansria, Oujda",
                            City = "Oujda",
                            Email = "meryem.fassi@gmail.com",
                            FirstName = "Meryem",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Fassi",
                            Phone = "0689012345"
                        },
                        new
                        {
                            PersonID = 9,
                            Address = "Dakhla, Meknes",
                            City = "Meknes",
                            Email = "hamza.radi@live.com",
                            FirstName = "Hamza",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Radi",
                            Phone = "0690123456"
                        },
                        new
                        {
                            PersonID = 10,
                            Address = "Mohammedia Center",
                            City = "Mohammedia",
                            Email = "salma.amrani@gmail.com",
                            FirstName = "Salma",
                            Gender = "F",
                            IsActive = true,
                            LastName = "Amrani",
                            Phone = "0601234567"
                        },
                        new
                        {
                            PersonID = 11,
                            Address = "Ait Alla , Tabia , Azilal",
                            City = "Azilal",
                            Email = "Freeh11@gmail.com",
                            FirstName = "Abdenabi",
                            Gender = "M",
                            IsActive = true,
                            LastName = "Khaldi",
                            Phone = "0644353219"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Librarian"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.BookCopy", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrowing", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.BookCopy", "BookCopy")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookCopyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Member", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LibraryManagement.Domain.Entities.Member", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("LibraryManagement.Domain.Entities.User", "PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.BookCopy", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
